%YAML:1.0


base_config: "../base.yaml"

sdf_iter_step: 5000
gs_iter_step: 60000

leaf_sizes: 0.4
bce_sigma: 1.0 # if get floaters, increase this value

preload: 0 # 0: disable; 1: enable # accelerate the loading process but will cost more memory
llff: 1 # 0: disable; 1: enable; every 8 frame will be used for evaluation

sh_degree: 3
bck_color: 1 # 0: black background; 1: white background; 2: discourage transparancy; degenerate results

prefilter: 0 # 0: disable; PSNR(SSIM) threshold; prefilter image according to sequential ssim: https://blog.csdn.net/weixin_43135178/article/details/118497369
max_time_diff_camera_and_pose: 0.01
max_time_diff_lidar_and_pose: 0.01

# dataset_type
#   Replica = 0,
#   R3live = 1,
#   NeuralRGBD = 2,
#   KITTI = 3,
#   FastLivo = 4,
#   Oxford Spires = 5,
#   FJ = 6,
dataset_type: 6
color_path: "colmap/images"
color_pose_path: "colmap/prior/images.txt"
color_pose_type: 4
color_pose_w2c: 1
depth_path: "depths"
depth_pose_path: "depths/lidar_pose.txt"
depth_pose_type: 5
# DepthType { Image = 0, PLY = 1, BIN = 2, PCD = 3 }
depth_type: 3

frame_rate: 10
min_range: 1
max_range: 100
ds_pt_num: 4000 # downsampled point number
max_pt_num: 5000000

outlier_remove: 1 # unnecessary for static scenes
outlier_dist: 0.05
outlier_removal_interval: 4000

# visualization
vis_resolution: 0.1 # better no more than leaf_sizes or will miss faces
export_resolution: 0.05
fps: 10

camera:
   model: 0 # 0: pinhole; 1: equidistant
   width: 4048
   height: 3040
   scale: 0.5

   fx: 612.5
   fy: 612.5
   cx: 2024
   cy: 1520

map:
   map_size: 300